export const fontNames = [
  {
    fontName: "Doto",
    short: "h21",
    tag: "dr",
  },
  {
    fontName: "Doto Rounded",
    short: "h22",
    tag: "drr",
  },
  {
    fontName: "Geist",
    short: "h11",
    tag: "geistRegular",
  },
  {
    fontName: "Monteserrat",
    short: "h23",
    tag: "mr",
  },
  {
    fontName: "Nunito",
    short: "h24",
    tag: "nr",
  },
  {
    fontName: "Open Sans",
    short: "h25",
    tag: "or",
  },
  //   {
  //     fontName: "PlayWrite",
  //     short: "h26",
  //     tag: "pr",
  //   },
  {
    fontName: "Roboto",
    short: "h27",
    tag: "r",
  },
  {
    fontName: "Roboto Mono",
    short: "h28",
    tag: "rr",
  },
  {
    fontName: "Roboto Slab",
    short: "h29",
    tag: "rsr",
  },
  {
    fontName: "Syne Mono",
    short: "h30",
    tag: "smr",
  },
  {
    fontName: "Titillium Web",
    short: "h31",
    tag: "tr",
  },
  {
    fontName: "Ubuntu",
    short: "h32",
    tag: "ur",
  },
  {
    fontName: "Ubuntu Mono",
    short: "h33",
    tag: "umr",
  },
  {
    fontName: "Verdana",
    short: "h34",
    tag: "v",
  },
  {
    fontName: "Mouser",
    short: "h35",
    tag: "mo",
  },
  {
    fontName: "Irish",
    short: "h36",
    tag: "iub",
  },
  // {
  //   fontName: "Stranger Back",
  //   short: "h37",
  //   tag: "sbitn",
  // },
  {
    fontName: "Typewriter One",
    short: "h38",
    tag: "dt1",
  },
  // {
  //   fontName: "Jot Spray",
  //   short: "h39",
  //   tag: "jspr",
  // },
  {
    fontName: "Typewriter Two",
    short: "h40",
    tag: "ot",
  },
  {
    fontName: "Garamond",
    short: "h41",
    tag: "gr",
  },
  {
    fontName: "Syne Regular",
    short: "h42",
    tag: "sr",
  },
  // {
  //   fontName: "Typewriter Three",
  //   short: "h41",
  //   tag: "wtdr",
  // },
];

export const fontSize = [
  "10px",
  "12px",
  "14px",
  "16px",
  "18px",
  "20px",
  "22px",
  "24px",
  "26px",
  "28px",
  "30px",
  "32px",
  "34px",
  "36px",
  "38px",
  "40px",
  "42px",
  "44px",
  "46px",
  "48px",
  "50px",
  "52px",
  "54px",
  "56px",
  "58px",
  "60px",
  "62px",
  "64px",
  "66px",
  "68px",
  "70px",
  "72px",
  "74px",
  "76px",
  "78px",
  "80px",
  "82px",
  "84px",
  "86px",
  "88px",
  "90px",
];

export const toolbarItems = [
  { itemName: "Speech to Text", id: 1, itemTag: "T1" },
  { itemName: "Undo", id: 2, itemTag: "T2" },
  { itemName: "Redo", id: 3, itemTag: "T3" },
  { itemName: "Toggle Font Style", id: 4, itemTag: "T4" },
  { itemName: "Toggle Font Size", id: 5, itemTag: "T5" },
  { itemName: "Toggle Bold", id: 6, itemTag: "T6" },
  { itemName: "Toggle Italics", id: 7, itemTag: "T7" },
  { itemName: "Toggle Underline", id: 8, itemTag: "T8" },
  { itemName: "Toggle Strikethrough", id: 9, itemTag: "T9" },
  { itemName: "Toggle Highlight", id: 10, itemTag: "T10" },
  { itemName: "Toggle Horizontal Rule", id: 11, itemTag: "T11" },
  { itemName: "Toggle Heading", id: 12, itemTag: "T12" },
  { itemName: "Toggle Quote", id: 13, itemTag: "T13" },
  { itemName: "Toggle Subscript", id: 14, itemTag: "T14" },
  { itemName: "Toggle Superscript", id: 15, itemTag: "T15" },
  { itemName: "Toggle Bullet List", id: 16, itemTag: "T16" },
  { itemName: "Toggle Number List", id: 17, itemTag: "T17" },
  { itemName: "Toggle Checkbox", id: 18, itemTag: "T18" },
  { itemName: "Toggle Text Alignment", id: 19, itemTag: "T19" },
  { itemName: "Clear Format", id: 20, itemTag: "T20" },
  { itemName: "Indent Item", id: 21, itemTag: "T21" },
  { itemName: "Unindent Item", id: 22, itemTag: "T22" },
];

export const TaggedItem = [
  { itemTag: "T1", tag: "" },
  { itemTag: "T2", tag: "" },
  { itemTag: "T3", tag: "" },
  { itemTag: "T4", tag: "" },
  { itemTag: "T5", tag: "" },
  { itemTag: "T6", tag: "" },
  { itemTag: "T7", tag: "" },
  { itemTag: "T8", tag: "" },
  { itemTag: "T9", tag: "" },
  { itemTag: "T10", tag: "" },
  { itemTag: "T11", tag: "" },
  { itemTag: "T12", tag: "" },
  { itemTag: "T13", tag: "" },
  { itemTag: "T14", tag: "" },
  { itemTag: "T15", tag: "" },
  { itemTag: "T16", tag: "" },
  { itemTag: "T17", tag: "" },
  { itemTag: "T18", tag: "" },
  { itemTag: "T19", tag: "" },
  { itemTag: "T20", tag: "" },
  { itemTag: "T21", tag: "" },
  { itemTag: "T22", tag: "" },
];

export const toolTemplate = `{"root":{"children":[{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-family: smr;","text":"For Bold","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":2,"mode":"normal","style":"font-family: smr;","text":"For Italic","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":2,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":8,"mode":"normal","style":"font-family: smr;","text":"For Underline","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":8,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":4,"mode":"normal","style":"font-family: smr;","text":"For Strikethrough","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":4,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":128,"mode":"normal","style":"font-family: smr;","text":"For Highlight","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":128,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-family: smr;font-size: 60px;","text":"For Heading 1","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":"font-family: smr;font-size: 60px;"},{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-family: smr;font-size: 50px;","text":"For Heading 2","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":"font-family: smr;font-size: 50px;"},{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-family: smr;font-size: 40px;","text":"For Heading 3","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":"font-family: smr;font-size: 40px;"},{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-family: smr;font-size: 30px;","text":"For Heading 4","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":"font-family: smr;font-size: 30px;"},{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-family: smr;font-size: 20px;","text":"For Heading 5","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":"font-family: smr;font-size: 20px;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Qoute","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"quote","version":1},{"children":[{"detail":0,"format":64,"mode":"normal","style":"font-family: smr;","text":"For Superscript","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":64,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":32,"mode":"normal","style":"font-family: smr;","text":"For Subscript","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":32,"textStyle":"font-family: smr;"},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Unordered list","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Ordered list","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"number","start":1,"tag":"ol"},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Checkbox","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"checked":false,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"check","start":1,"tag":"ul"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Left align","type":"text","version":1}],"direction":"ltr","format":"left","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Right align","type":"text","version":1}],"direction":"ltr","format":"right","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Center align","type":"text","version":1}],"direction":"ltr","format":"center","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Justify align","type":"text","version":1}],"direction":"ltr","format":"justify","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Outdent","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"For Indent","type":"text","version":1}],"direction":"ltr","format":"","indent":1,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;font-size: 18px;","text":"For Changing font size","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;font-size: 18px;"},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"type":"horizontalrule","version":1},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}`;

export const lexicalEdit = `{"root":{"children":[{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-size: 50px;font-family: smr;","text":"2023-02-08 ","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":""},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":""},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-size: 15px;font-family: smr;","text":"Today has been a busy day as always. I woke up early, had my morning coffee and started working on my current project. It's a new software application for a client, and I'm working on improving the user interface. I'm really excited about this project and I feel like I'm making great progress. Later in the day, I had a meeting with my team to discuss the progress of the project and to assign tasks for the next sprint. I'm lucky to be part of a great team, ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-size: 15px;font-family: smr;","text":"And i feel like we work well together to achieve our goals. In the afternoon, I took a break from coding and attended a workshop on the latest technologies in software development. It was a great opportunity to learn and network with my peers in the industry. I also had a chance to ask questions and get advice from some of the experts in the field. D Before I knew it, it was already evening, and I had to wrap up my work for the day. I made sure to review my code and do some testing to ensure everything is working as expected.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-size: 15px;font-family: smr;"},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""},{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-size: 50px;font-family: smr;","text":"Spotify Chrome Extension Idea :","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""},{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":""},{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":""},{"children":[{"detail":0,"format":1,"mode":"normal","style":"font-size: 30px;font-family: smr;","text":"React File Structure","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":1,"textStyle":"font-size: 30px;font-family: smr;"},{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":""},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"spotify-chrome-extension/ ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"├── public/ ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"│ └── index.html ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#Root","type":"hashtag","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":" ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"├── src/ ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"│ ├── components/ ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"│ │ ├── Controls.jsx ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#Controls","type":"hashtag","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":" ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"│ │ └── SongInfo.jsx ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#Song","type":"hashtag","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":" ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"│ ├── App.jsx ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#Main","type":"hashtag","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":" ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"│ ├── index.css ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#Tailwind","type":"hashtag","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":" ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"│ └── index.js ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#React","type":"hashtag","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":" ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"├── tailwind.config.js ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#Tailwind","type":"hashtag","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":" ","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"},{"children":[{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"├── package.json ","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"font-family: smr;","text":"#Dependencies","type":"hashtag","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0,"textStyle":"font-family: smr;"}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}`;

const dayNamesShort = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const monthNamesShort = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "June",
  "July",
  "Aug",
  "Sept",
  "Aug",
  "Nov",
  "Dec",
];
const monthNamesLong = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
const dayNamesLong = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

const TempData = [
  {
    Title: "AI in Everyday Life",
    SubTitle: "Rank higher with proven SEO methods.",
    Date: "Mar 26, 2024",
    Topics: ["Automation", "Data Science", "No-Code"],
    Tags: 45,
    Links: 9,
    Attachments: 45,
  },
  {
    Title: "AI in Everyday Life",
    SubTitle: "Rank higher with proven SEO methods.",
    Date: "Oct 18, 2024",
    Topics: ["Cloud", "Automation", "Engineering", "Data Science"],
    Tags: 51,
    Links: 37,
    Attachments: 9,
  },
  {
    Title: "Building Scalable Web Apps",
    SubTitle: "Beyond Bitcoin – real-world blockchain applications.",
    Date: "Dec 12, 2024",
    Topics: ["Quantum Computing", "Cloud", "API"],
    Tags: 5,
    Links: 43,
    Attachments: 35,
  },
  {
    Title: "Game Development with Unity",
    SubTitle: "A complete guide to modern web development.",
    Date: "Sep 23, 2024",
    Topics: ["Data Science", "AI", "Cloud", "API"],
    Tags: 36,
    Links: 53,
    Attachments: 38,
  },
  {
    Title: "Cloud Computing Trends",
    SubTitle: "Data-driven decision making for success.",
    Date: "Aug 23, 2024",
    Topics: ["Automation", "Cybersecurity", "Cloud"],
    Tags: 16,
    Links: 39,
    Attachments: 44,
  },
  {
    Title: "AI in Everyday Life",
    SubTitle: "Creating inclusive digital experiences.",
    Date: "Jun 08, 2024",
    Topics: ["UI/UX", "No-Code"],
    Tags: 15,
    Links: 34,
    Attachments: 10,
  },
  {
    Title: "AI in Everyday Life",
    SubTitle: "Creating inclusive digital experiences.",
    Date: "Feb 10, 2024",
    Topics: ["UI/UX", "Game Dev"],
    Tags: 29,
    Links: 49,
    Attachments: 6,
  },
  {
    Title: "Mastering React Hooks",
    SubTitle: "Latest trends in cloud adoption.",
    Date: "Sep 15, 2024",
    Topics: ["Mobile", "Design", "Engineering"],
    Tags: 23,
    Links: 52,
    Attachments: 11,
  },
  {
    Title: "The Future of Mobile Development",
    SubTitle: "Latest trends in cloud adoption.",
    Date: "Sep 20, 2024",
    Topics: ["Cloud", "API"],
    Tags: 19,
    Links: 35,
    Attachments: 18,
  },
  {
    Title: "Designing for Accessibility",
    SubTitle: "No-code solutions for developers and non-tech users.",
    Date: "Sep 28, 2024",
    Topics: ["No-Code", "Automation"],
    Tags: 48,
    Links: 54,
    Attachments: 25,
  },
  {
    Title: "Automating Workflows with AI",
    SubTitle: "Reducing API latency for better performance.",
    Date: "May 14, 2024",
    Topics: ["SEO", "AI", "Quantum Computing"],
    Tags: 28,
    Links: 59,
    Attachments: 55,
  },
  {
    Title: "Designing for Accessibility",
    SubTitle: "Building immersive gaming experiences.",
    Date: "Jan 02, 2024",
    Topics: ["Engineering", "Cybersecurity", "Design", "Mobile"],
    Tags: 11,
    Links: 4,
    Attachments: 14,
  },
  {
    Title: "Cybersecurity in 2024",
    SubTitle: "Building immersive gaming experiences.",
    Date: "Jan 24, 2024",
    Topics: ["API", "Game Dev", "Blockchain"],
    Tags: 58,
    Links: 33,
    Attachments: 32,
  },
  {
    Title: "Designing for Accessibility",
    SubTitle: "Rank higher with proven SEO methods.",
    Date: "Oct 11, 2024",
    Topics: ["Cybersecurity", "Quantum Computing", "Mobile", "Design"],
    Tags: 28,
    Links: 32,
    Attachments: 53,
  },
  {
    Title: "Automating Workflows with AI",
    SubTitle: "Creating inclusive digital experiences.",
    Date: "Jun 15, 2024",
    Topics: ["Design", "AI"],
    Tags: 22,
    Links: 48,
    Attachments: 54,
  },
];

export {
  dayNamesLong,
  dayNamesShort,
  monthNamesShort,
  monthNamesLong,
  TempData,
};
